### ISSUE TITLE
bin instead of xbin

### ISSUE THREAD

**Issue by jancm** [Magisk-Modules-Repo/dnscrypt-proxy#33]
2 points.
First - make sure you close https://github.com/Magisk-Modules-Repo/dnscrypt-proxy/issues/31 ASAP otherwise the module will be removed from the Magisk repo come May 1.

Next - while you're fixing that can you also, in the case where the phone doesn't have a native xbin, install the binary to bin instead. Installing to xbin in such cases has proven problematic for multiple modules.

**Comment by bluemeda** [comment]
I just created new branch with new magisk requirement.
