### ISSUE TITLE
v2.8.2 problem of connection

### ISSUE THREAD

**Issue by lucenera** [Magisk-Modules-Repo/dnscrypt-proxy#37]
The module is installed, but there is no connection to the network.  Turning off the module everything works again. Until the penultimate version worked well.

**Comment by Skcyte** [comment]
Same. I updated from 2.8.0. Had to rollback.

**Comment by WhiCCX0** [comment]
Me too, ssrr vpn can't work and wifi can't connect

**Comment by tyblib** [comment]
I have same issue here

**Comment by pundoo** [comment]
Same here! No connection.

**Comment by lecahel** [comment]
https://github.com/Magisk-Modules-Repo/dnscrypt-proxy/blob/bc007fbf63f49195f1617ef4b1f5417a67c74cd1/install.sh#L204

dnscrypt-proxy daemon is not executed due to permission ploblem

maybe we need to change xbin to bin

**Comment by bluemeda** [comment]
Check for the new release.

**Comment by lucenera** [comment]
Now there is another problem. When you choose to create a new configuration it does not create the file.  I manually created the file renaming the example one, but the listen_address is always busy even if I change it.  Result: it still does not work.

**Comment by hengkidermawan** [comment]
update 2.8.3 still no connection, back to 2.8.0 (I think it best for my phone )

**Comment by lucenera** [comment]
How can I install zip from github?? Tell me no magisk module.

**Comment by gorillap** [comment]
Confirmed.
OP6 - OOS 9.0.5
2.8.1 working fine. Upgraded to 2.8.3 and no internet connection. Disabled module and connection back up.

**Comment by pundoo** [comment]
@bluemeda Also, You shouldn't place the files under 'dnscrypt-proxy-*' (or any) folder. Doing that makes it unrecognizable as a module by Magisk, when flashing manually (also flashing in Recovery says 'invalid zip', if I remember correctly). Instead ZIP them directly.

**Comment by bluemeda** [comment]
check v3.8.4

**Comment by gorillap** [comment]
Tried 2.8.4.
Still broken
