### ISSUE TITLE
2.83 config file issues.

### ISSUE THREAD

**Issue by jancm** [Magisk-Modules-Repo/dnscrypt-proxy#39]
2 separate issues related to config files
1) re-use old config doesn't work, thinks it's an initial install even if it's not.
2) initial install doesn't create new config.

Causes of problems:
1) $MODPATH points to modules_update rather than modules so checking in there for an existing file fails.
2) you're attempting to copy from
$MODPATH/system/etc/example-dnscrypt-proxy.toml
and it should be
$MODPATH/system/etc/dnscrypt-proxy/example-dnscrypt-proxy.toml

Code to solve issues in option.sh starting at line 65:

CONFIG_FILE=$MODPATH/system/etc/dnscrypt-proxy/dnscrypt-proxy.toml
OLD_CONFIG_FILE=$(echo $CONFIG_FILE|sed s/modules_update/modules/)

if $FUNCTION; then
  ui_print "Replace old config"
  ui_print " "
  cp -af $MODPATH/system/etc/dnscrypt-proxy/example-dnscrypt-proxy.toml $CONFIG_FILE
  sed -i -e 's/127.0.0.1:53/127.0.0.1:5354/g' $CONFIG_FILE
  sed -i -e 's/\[::1\]:53/\[::1\]:5354/g' $CONFIG_FILE
else
  if [ -f "$OLD_CONFIG_FILE" ]; then
    ui_print "* Copying old config file"
    cp $OLD_CONFIG_FILE $CONFIG_FILE
  else
    abort "First install have to choose replace mode"
  fi
fi

**Comment by bluemeda** [comment]
@jancm done. Sorry for this. currently I have no rooted device. Still waiting UBL time from xiaomi.
